# Import Libraries

In [ ]:
import pandas as pd
import numpy as np

# Import Datasets

Use the Pandas method <b>read_excel</b> to load the data from the web address. Set the parameter  "names" equal to the Python list "headers".

In [ ]:
df = pd.read_excel('/content/Inventory_DataSet.xlsx')

In [ ]:
headers = df.columns.tolist()

print(headers)

['ProductName', 'Description', 'Product Image', 'Product Cateogy Name', 'Model Number', 'Serial Number', 'StockLevel', 'ReorderPoint', 'Supplier Name', 'Supplier Mail', 'Supplier  Contact', 'Order Date', 'Quantity', 'Order Status']

 Use the method <b>head()</b> to display the first five rows of the dataframe.

In [ ]:
# To see what the data set looks like, we'll use the head() method.
df.head()

,ProductName,Description,Product Image,Product Cateogy Name,Model Number,Serial Number,StockLevel,ReorderPoint,Supplier Name,Supplier Mail,Supplier Contact,Order Date,Quantity,Order Status
0,Cisco ISR 1101,ISR 1101 4 Ports GE Ethernet WAN Router,NaN,Router,XYZ123,6a38028c-6a71-4f44-b8f6-253bc7086a0a,500,150,Cisco,abcd@mail.com,1234567890,2023-01-15 00:00:00,500,Deliverd
1,HP 5406zl,HP ProCurve Switch 5406zl,NaN,Switch,ABC456,7edc108e-45e0-4997-bc59-17852d16b689,300,100,HP,abhp@mail.com,1980762345,2023-11-05 00:00:00,300,Deliverd
2,DOCSIS 3.1 Cable Modem,Superfast speeds up to 10 gigabits per second ...,modem.jpg,Modem,LMN789,e41e2e16-2945-4c0c-a584-48935742fe94,200,50,Netgear,Neger@mail.com,9256476541,2023-08-06 00:00:00,200,Deliverd
3,Cellular Duplexer Rx,A multiplexer product that is RoHS6 compliant,NaN,Multiplexer,DSC423,6aac9135-9ceb-4535-a13a-fc04ad8dadd5,200,50,Broadcom,brcom@mail.com,1759731673,2023-05-16 00:00:00,200,Deliverd
4,SBB100 Splitter Trough Block,Splitter block with copper-aluminium monopie...,splitter.jpg,Splitter,BGH678,b01f5fea-f863-441e-9150-c5595caa9f01,400,75,BELL,blee@mail.com,1256476893,2023-10-06 00:00:00,400,Deliverd

As we can see, several question marks appeared in the dataframe; those are missing values which may hinder our further analysis.

<div>So, how do we identify all those missing values and deal with them?</div>

<b>How to work with missing data?</b>

Steps for working with missing data:

<ol>
    <li>Identify missing data</li>
    <li>deal with missing data</li>
    <li>correct data format</li>
</ol>

<h1 id="identify_handle_missing_values">Identify and handle missing values</h1>

<h2 id="identify_missing_values">Identify missing values</h2>
<h3>Convert "?" to NaN</h3>
In the car dataset, missing data comes with the question mark "?".
We replace "?" with NaN (Not a Number), which is Python's default missing value marker, for reasons of computational speed and convenience. Here we use the function:
 <pre>.replace(A, B, inplace = True) </pre>
to replace A by B

In [ ]:
# replace "?" to NaN
df.replace("?", np.nan, inplace = True)
df.head(5)

,ProductName,Description,Product Image,Product Cateogy Name,Model Number,Serial Number,StockLevel,ReorderPoint,Supplier Name,Supplier Mail,Supplier Contact,Order Date,Quantity,Order Status
0,Cisco ISR 1101,ISR 1101 4 Ports GE Ethernet WAN Router,NaN,Router,XYZ123,6a38028c-6a71-4f44-b8f6-253bc7086a0a,500,150,Cisco,abcd@mail.com,1234567890,2023-01-15 00:00:00,500,Deliverd
1,HP 5406zl,HP ProCurve Switch 5406zl,NaN,Switch,ABC456,7edc108e-45e0-4997-bc59-17852d16b689,300,100,HP,abhp@mail.com,1980762345,2023-11-05 00:00:00,300,Deliverd
2,DOCSIS 3.1 Cable Modem,Superfast speeds up to 10 gigabits per second ...,modem.jpg,Modem,LMN789,e41e2e16-2945-4c0c-a584-48935742fe94,200,50,Netgear,Neger@mail.com,9256476541,2023-08-06 00:00:00,200,Deliverd
3,Cellular Duplexer Rx,A multiplexer product that is RoHS6 compliant,NaN,Multiplexer,DSC423,6aac9135-9ceb-4535-a13a-fc04ad8dadd5,200,50,Broadcom,brcom@mail.com,1759731673,2023-05-16 00:00:00,200,Deliverd
4,SBB100 Splitter Trough Block,Splitter block with copper-aluminium monopie...,splitter.jpg,Splitter,BGH678,b01f5fea-f863-441e-9150-c5595caa9f01,400,75,BELL,blee@mail.com,1256476893,2023-10-06 00:00:00,400,Deliverd

Identify_missing_values

<h2>Evaluating for Missing Data</h2>

The missing values are converted to default. We use the following functions to identify these missing values. There are two methods to detect missing data:

<ol>
    <li><b>.isnull()</b></li>
    <li><b>.notnull()</b></li>
</ol>
The output is a boolean value indicating whether the value that is passed into the argument is in fact missing data.

In [ ]:
missing_data = df.isnull()
missing_data.head(5)

,ProductName,Description,Product Image,Product Cateogy Name,Model Number,Serial Number,StockLevel,ReorderPoint,Supplier Name,Supplier Mail,Supplier Contact,Order Date,Quantity,Order Status
0,False,False,True,False,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False

"True" stands for missing value, while "False" stands for not missing value.

<h2>Count missing values in each column</h2>
<p>
Using a for loop in Python, we can quickly figure out the number of missing values in each column. As mentioned above, "True" represents a missing value, "False"  means the value is present in the dataset.  In the body of the for loop the method  ".value_counts()"  counts the number of "True" values.
</p>

In [ ]:
for column in headers:
    print(column)
    print (missing_data[column].value_counts())
    print("")

ProductName
ProductName
False    500
Name: count, dtype: int64

Description
Description
False    500
Name: count, dtype: int64

Product Image
Product Image
True     380
False    120
Name: count, dtype: int64

Product Cateogy Name
Product Cateogy Name
False    500
Name: count, dtype: int64

Model Number
Model Number
False    500
Name: count, dtype: int64

Serial Number
Serial Number
False    500
Name: count, dtype: int64

StockLevel
StockLevel
False    500
Name: count, dtype: int64

ReorderPoint
ReorderPoint
False    500
Name: count, dtype: int64

Supplier Name
Supplier Name
False    500
Name: count, dtype: int64

Supplier Mail
Supplier Mail
False    500
Name: count, dtype: int64

Supplier  Contact
Supplier  Contact
False    500
Name: count, dtype: int64

Order Date
Order Date
False    500
Name: count, dtype: int64

Quantity
Quantity
False    500
Name: count, dtype: int64

Order Status
Order Status
False    500
Name: count, dtype: int64

In [ ]:
df['Product Image'] = df['Product Image'].replace([None, ''], pd.NA)

In [ ]:
df['Product Image'] = df['Product Image'].replace(['', None, 'N/A'], pd.NA)

df['Product Image'] = df['Product Image'].str.strip()

df['Product Image'] = df['Product Image'].fillna('No image')

missing_count = df['Product Image'].isna().sum()

In [ ]:
print(df['Product Image'].isnull().sum())

0

In [ ]:
df.head()

,ProductName,Description,Product Image,Product Cateogy Name,Model Number,Serial Number,StockLevel,ReorderPoint,Supplier Name,Supplier Mail,Supplier Contact,Order Date,Quantity,Order Status
0,Cisco ISR 1101,ISR 1101 4 Ports GE Ethernet WAN Router,No image,Router,XYZ123,6a38028c-6a71-4f44-b8f6-253bc7086a0a,500,150,Cisco,abcd@mail.com,1234567890,2023-01-15 00:00:00,500,Deliverd
1,HP 5406zl,HP ProCurve Switch 5406zl,No image,Switch,ABC456,7edc108e-45e0-4997-bc59-17852d16b689,300,100,HP,abhp@mail.com,1980762345,2023-11-05 00:00:00,300,Deliverd
2,DOCSIS 3.1 Cable Modem,Superfast speeds up to 10 gigabits per second ...,modem.jpg,Modem,LMN789,e41e2e16-2945-4c0c-a584-48935742fe94,200,50,Netgear,Neger@mail.com,9256476541,2023-08-06 00:00:00,200,Deliverd
3,Cellular Duplexer Rx,A multiplexer product that is RoHS6 compliant,No image,Multiplexer,DSC423,6aac9135-9ceb-4535-a13a-fc04ad8dadd5,200,50,Broadcom,brcom@mail.com,1759731673,2023-05-16 00:00:00,200,Deliverd
4,SBB100 Splitter Trough Block,Splitter block with copper-aluminium monopie...,splitter.jpg,Splitter,BGH678,b01f5fea-f863-441e-9150-c5595caa9f01,400,75,BELL,blee@mail.com,1256476893,2023-10-06 00:00:00,400,Deliverd

In [24]:
# Save the cleaned DataFrame to an Excel file
df.to_excel('Inventory_DataSet.xlsx', index=False, sheet_name='Final Dataset')